### PR TITLE
Settings page tabs not appearing when eRoom - Zoom Meetings & Webinar…

### LINKED ISSUE #174: Settings page tabs not appearing when eRoom - Zoom Meetings & Webinar plugin is activated
https://wordpress.org/plugins/eroom-zoom-meetings-webinar/

### PR DESCRIPTION
**Pull request by reygcalantaol**
@polevaultweb 

For some reason compiling the wp-optionkit without changing on the source fixed the issue.
Resolves https://github.com/WPUserManager/wp-user-manager/issues/174

### CODE REVIEW

**Comment by polevaultweb** [comment]
@reygcalantaol did you recompile with yarn or npm?

**Comment by reygcalantaol** [comment]
@polevaultweb 
I compiled with npm.

**Comment by polevaultweb** [comment]
`npm run build`? I'm running that and it's not producing the same changes to the files.

**Comment by reygcalantaol** [comment]
> 
> 
> `npm run build`? I'm running that and it's not producing the same changes to the files.

@polevaultweb 
Yes.
What I did first was to install dependencies.
npm install

**Pull request closed without merging**
